config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "static_pages#home"
    resources :categories, except: [:show]
    resources :books
  end
  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  resources :users, except: [:destroy]
  resources :books, only: [:index, :show] do
    resources :reviews do
      resources :comments
    end
    resources :rates, except: [:destroy]
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  has_many :reading_books, dependent: :destroy
  has_many :rates, dependent: :destroy
  has_many :reviews, dependent: :destroy

  mount_uploader :image, PictureUploader

  VALID_DATE_REGEX = /\A\d{4}\-(?:0?[1-9]|1[0-2])\-(?:0?[1-9]|[1-2]\d|3[01])\z/i

  validates :name, presence: true, length: {maximum: 50}, uniqueness: true
  validates :author, presence: true, length: {maximum: 50}
  validates :url, presence: true
  validates :description, presence: true
  validates :publish_date, presence: true, format: {with: VALID_DATE_REGEX}

  scope :hottest, -> do
    order(rating: :desc).limit Settings.per_page
  end
  scope :search, ->search do
    where("name like ?", "%#{search}%").limit Settings.limit_book
  end
  scope :name_or_author, ->search do
    where "name LIKE ? OR author LIKE ?", "%#{search}%", "%#{search}%"
  end
  scope :newest, ->{order created_at: :desc}
  scope :except_id, ->id do
    where("id != ?", id).limit Settings.limit_book
  end
  scope :by_category, ->id do
    if id
      where("category_id != ?", id)
    else
      newest
    end
  end
  scope :search_name_or_author, ->search do
    if search
      name_or_author search
    else
      newest
    end
  end

  private
  def picture_size
    if image.size > Settings.size_image.megabytes
      errors.add :image, Settings.alert_size_image
    end
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :verify_access
  before_action :load_categories, only: [:new, :edit]
  before_action :load_book, except: [:index, :create, :new]
  layout "admin_application"

  def index
    @books = Book.search_name_or_author(params[:key_seach]).newest
      .paginate page: params[:page], per_page: Settings.per_page
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new book_params
    if @book.save
      flash[:info] = t "alert_result"
      redirect_to admin_books_url
    else
      @categories = Category.all
      render :new
    end
  end

  def show
    @reviews = @book.reviews.includes(:user, comments:[:user]).newest
      .paginate page: params[:page], per_page: Settings.per_page
  end

  def edit
  end

  def update
    if @book.update_attributes book_params
      flash[:info] = t "alert_result"
      redirect_to admin_books_url
    else
      @categories = Category.all
      render :edit
    end
  end

  def destroy
    unless @book
      respond_to do |format|
        format.js {render "admin/shared/fail_update_or_del.js.erb"}
      end
    else
      @book.destroy
      respond_to do |format|
        format.js
      end
    end
  end

  private
  def book_params
    params.require(:book).permit :name, :description, :author, :url, :image,
      :publish_date, :category_id
  end

  def load_book
    @book = Book.find_by id: params[:id]
    unless @book
      flash[:warning] = t "record_isnt_exist"
      redirect_to admin_books_url
    end
  end

  def load_categories
    @categories = Category.all
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :load_book, only: [:show]
  before_action :load_categories

  def show
    @books_relate = @book.category.books.except_id(@book.id).newest
    @reviews = @book.reviews.includes(:user, comments: :user).newest
      .paginate page: params[:page], per_page: Settings.per_page
    if logged_in?
      @review = @book.reviews.build
      @rate = @book.rates.build
    end
  end

  def index
    @books_search = Book.search(params[:search]).newest
    if params[:category].blank?
      @books = Book.newest.paginate page: params[:page],
        per_page: Settings.per_page
    else
      @category = Category.find_by id: params[:category]
      unless @category
        flash[:danger] = t "record_isnt_exist"
        redirect_to books_path
      else
        @books = @category.books.newest.paginate page: params[:page],
          per_page: Settings.per_page
      end
    end
  end

  private
  def load_book
    @book = Book.find_by id: params[:id]
    unless @book
      flash[:warning] = t "record_isnt_exist"
      redirect_to root_url
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper

  def show_rating string = ""
    rating = "<span class = '#{string}'>☆</span>"
    rating.html_safe
  end
end

app/views/admin/books/_list.html.erb
<table class="table table-striped table-bordered table-custom" cellspacing="0">
  <thead>
    <tr>
      <th class = "first-column"><%= t "no_number" %></th>
      <th><%= t "book_name" %></th>
      <th><%= t "book_author" %></th>
      <th><%= t "book_rating" %></th>
      <th><%= t "book_publish_date" %></th>
      <th class = "last-column"><%= t "action" %></th>
    </tr>
  </thead>
  <tbody id = "body_table_data">
    <% @books.each do |book| %>
      <tr>
        <td class = "first-column"><%= book.id %></td>
        <td><%= link_to book.name, admin_book_path(book) %></td>
        <td><%= book.author %></td>
        <td><%= book.rating %></td>
        <td><%= book.publish_date %></td>
        <td class = "last-column">
          <%= link_to t("edit_button"), edit_admin_book_path(book),
            class: "btn btn-warning btn-mn" %>
          <%= link_to t("delete_button"), admin_book_path(book),
            method: :delete, remote: true,
            data: {confirm: t("alert_confirm")},
            class: "btn btn-danger btn-mn btn-custom" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="col-md-12 top-20 padding-0 custom-div"><%= will_paginate %></div>

app/views/admin/books/destroy.js.erb
notify = $('.mess-area-du');
notify.html('<%= j render "admin/shared/succ_del" %>'');

app/views/admin/books/edit.html.erb
<div class="col-md-12 top-20 padding-0">
  <div class="col-md-12">
    <div class="panel">
      <div class="panel-heading">
        <h3><%= t "add_new" %></h3>
      </div>
      <div class="panel-body">
        <%= form_for [:admin, @book], html: {multipart: true},
          url: admin_book_path do |f| %>
          <% if @book.errors.any? %>
            <div class="row">
              <div class="col-md-6 mess-area-add">
                <div class="alert alert-danger alert-custom">
                  <button type="button" class="close closeNotify">
                    &times;
                  </button>
                  <% @book.errors.full_messages.each do |msg| %>
                    <p><%= msg %></p>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
          <div class="row">
            <div class="col-md-4">
              <%= f.label :name %>
              <%= f.text_field :name, placeholder: t("book_name"),
                class: "form-control" %>
            </div>
            <div class="col-md-4">
              <%= f.label :category_id %>
              <%= f.select :category_id,
                @categories.collect {|c| [c.name, c.id]}, {},
                {class: "form-control reset-select"} %>
            </div>
            <div class="col-md-4">
              <%= f.label :author %>
              <%= f.text_field :author, placeholder: t("book_author"),
                class: "form-control" %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4">
              <%= f.label :url %>
              <%= f.text_field :url, placeholder: t("book_url"),
                class: "form-control" %>
            </div>
            <div class="col-md-4">
              <%= f.label :publish_date,
                "#{t("book_publish_date")} #{t("book_date_format")}" %>
              <%= f.date_field :publish_date,
                placeholder: t("book_publish_date"),
                class: "form-control" %>
            </div>
          </div>
          <div class="row top-20">
            <div class="col-md-4 top-20">
              <div class="col-md-12 padding-0">
                <%= display_image @book, "img-thumbnail edit-book-img" %>
              </div>
              <div class="col-md-12 top-20 padding-0">
                <%= link_to t("change_button"), "javascript:;",
                  class: "btn btn-info btn-mn change-image" %>
                <%= f.file_field :image, class: "hidden", id: "hidden_input",
                  accept: "image/jpeg,image/gif,image/png" %>
                <span class = "new_image"></span>
              </div>
            </div>
            <div class="col-md-8">
              <%= f.label :description %>
              <%= f.text_area :description, rows: "10",
                class: "form-control" %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 top-20 padding-0">
              <div class="form-group col-md-3">
                <%= button_tag type: "submit",
                  class: "btn ripple btn-gradient btn-info" do %>
                  <div><span><%= t "update_button" %></span></div>
                <% end %>
              </div>
              <div class="form-group col-md-3">
                <%= button_tag type: "reset",
                  class: "btn ripple btn-gradient btn-default" do %>
                  <div><span><%= t "reset_button" %></span></div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/books/index.html.erb
<div class="col-md-12 top-20 padding-0">
  <div class="col-md-12">
    <div class="panel">
      <div class="panel-heading">
        <h3><%= t "show" %></h3>
      </div>
      <div class="panel-body">
        <div class="col-md-6 mess-area-du padding-0">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>">
              <button type="button" class="close closeNotify">&times;</button>
              <%= message %>
            </div>
          <% end %>
        </div>
        <div class="col-md-12 col-md-12-custom top-20 padding-0">
          <div class="col-md-4 padding-0">
            <%= form_tag admin_books_path, method: "GET",
              id: "my_form_search" do %>
              <%= text_field_tag :key_seach, params[:key_seach],
                placeholder: "#{t('book_name')} #{t('or')} #{t('book_author')}",
                class: "form-control reset-input search-input" %>
              <span class="glyphicon glyphicon-search form-control-feedback">
              </span>
            <% end %>
          </div>
          <div class="col-md-1 padding-0">
          </div>
          <div class="col-md-4 padding-0">
            <%= link_to t("add_new"), new_admin_book_path,
            class: "btn btn-info btn-mn" %>
          </div>
        </div>
        <div class = "clr"></div>
        <div class="responsive-table sort-table">
          <%= render "list" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/books/index.js.erb
$('.sort-table').html('<%= j render "admin/books/list" %>');

app/views/admin/books/new.html.erb
<div class="col-md-12 top-20 padding-0">
  <div class="col-md-12">
    <div class="panel">
      <div class="panel-heading">
        <h3><%= t "add_new" %></h3>
      </div>
      <div class="panel-body">
        <%= form_for [:admin, @book], html: {multipart: true} do |f| %>
          <% if @book.errors.any? %>
          <div class="row">
            <div class="col-md-6 mess-area-add">
              <%= render 'admin/shared/message_add', object: @book %>
            </div>
          </div>
          <% end %>
          <div class="row">
            <div class="col-md-4">
              <%= f.label :name %>
              <%= f.text_field :name, placeholder: t("book_name"),
                class: "form-control" %>
            </div>
            <div class="col-md-4">
              <%= f.label :category_id %>
              <%= f.select :category_id,
                @categories.collect {|c| [c.name, c.id]}, {},
                {class: "form-control reset-select"} %>
            </div>
            <div class="col-md-4">
              <%= f.label :author %>
              <%= f.text_field :author, placeholder: t("book_author"),
                class: "form-control" %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4">
              <%= f.label :url %>
              <%= f.text_field :url, placeholder: t("book_url"),
                class: "form-control" %>
            </div>
            <div class="col-md-4">
              <%= f.label :publish_date,
                "#{t("book_publish_date")} #{t("book_date_format")}" %>
              <%= f.date_field :publish_date,
                placeholder: t("book_publish_date"),
                class: "form-control" %>
            </div>
            <div class="col-md-4">
              <%= f.label :image %>
              <%= f.file_field :image,
                accept: "image/jpeg,image/gif,image/png" %>
            </div>
          </div>
          <div class="row top-20">
            <div class="col-md-8">
              <%= f.label :description %>
              <%= f.text_area :description, rows: "10",
                class: "form-control" %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 top-20 padding-0">
              <div class="form-group col-md-3">
                <%= button_tag type: "submit",
                  class: "btn ripple btn-gradient btn-info" do %>
                  <div><span><%= t "add_button" %></span></div>
                <% end %>
              </div>
              <div class="form-group col-md-3">
                <%= button_tag type: "reset",
                  class: "btn ripple btn-gradient btn-default" do %>
                  <div><span><%= t "reset_button" %></span></div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/books/show.html.erb
<div class="col-md-12 top-20 padding-0">
  <div class="col-md-12">
    <div class="panel">
      <div class="panel-heading">
        <h3><%= @book.name %></h3>
      </div>
      <div class="panel-body">
        <div class="col-md-4">
          <%= display_image @book, "img-responsive" %>
        </div>
        <div class="col-md-6">
          <div class="responsive-table">
            <table class="table table-striped table-bordered" width="100%"
              cellspacing="0">
              <tbody>
                <tr>
                  <th><%= t "book_name" %></th>
                  <th><%= @book.name %></th>
                </tr>
                <tr>
                  <th><%= t "book_category" %></th>
                  <th><%= @book.category.name %></th>
                </tr>
                <tr>
                  <th><%= t "book_author" %></th>
                  <th><%= @book.author %></th>
                </tr>
                <tr>
                  <th><%= t "book_rating" %></th>
                  <th><%= @book.rating %></th>
                </tr>
                <tr>
                  <th><%= t "book_url" %></th>
                  <th><%= @book.url %></th>
                </tr>
                <tr>
                  <th><%= t "book_publish_date" %></th>
                  <th><%= l @book.publish_date %></th>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        <div class = "col-md-12 top-20">
          <div class = "col-md-10 padding-0"><%= @book.description %></div>
        </div>
      </div>
    </div>
  </div>
</div>
<% if @reviews.any? %>
  <div class="col-md-12 col-sm-12 profile-v1-body">
    <div class="col-md-9">
      <div class="panel-heading">
        <h3>
          <%= "#{@book.reviews.count}  #{t('book_review_for')}" %>
          <strong><%= @book.name %></strong>
        </h3>
      </div>
      <% @reviews.each do |review| %>
        <div class="panel box-v7">
          <div class="panel-body">
            <div class="col-md-12 padding-0 box-v7-header">
              <div class="col-md-12 padding-0">
                <div class="col-md-10 padding-0">
                  <%= link_to image_tag(review.user.image,
                    class: "box-v7-avatar pull-left"), "#" %>
                  <h4><%= review.user.name %></h4>
                  <p>
                    <%= "#{time_ago_in_words(review.created_at)}" %>
                    <%= t("time_ago") %>
                  </p>
                </div>
                <div class="col-md-2 padding-0">
                  <div class="btn-group right-option-v1">
                    <i class="glyphicon glyphicon-option-vertical box-v7-menu"
                      data-toggle="dropdown"></i>
                    <ul class="dropdown-menu" role="menu">
                      <li><%= link_to t("delete_button"), "#" %></li>
                      <li><%= link_to t("goto_button"), "#" %></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-12 padding-0 box-v7-body">
            <h4 class="media-heading"><%= review.title %></h4>
              <p><%= review.content %></p>
              <div class="col-md-12 top-20">
                <i class="glyphicon glyphicon-thumbs-up"></i> 2819
                <i class="glyphicon glyphicon-comment"></i> 2819
              </div>
            </div>
            <div class="col-md-12 padding-0 box-v7-comment">
              <% review.comments.each do |comment| %>
                <div class="media">
                  <div class="media-left">
                  <%= link_to image_tag(comment.user.image,
                      class: "media-object box-v7-avatar"), "#" %>
                  </div>
                  <div class="media-body">
                    <h4 class="media-heading"><%= comment.user.name %></h4>
                    <p><%= comment.content %></p>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
      <%= will_paginate @reviews %>
    </div>
  </div>
<% end %>