config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "static_pages#home"
    resources :categories, except: [:show]
    resources :books
  end
  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  resources :users, except: [:destroy]
  resources :books, only: [:index, :show] do
    resources :reviews do
      resources :comments
    end
    resources :rates, except: [:destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save {email.downcase!}

  enum role: [:admin, :mod, :user]

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_secure_password
  validates :name,  presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}, on: :create
  validates :password, length: {minimum: 6}, allow_blank: true, on: :update

  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: :follower_id, dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: :followed_id, dependent: :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :reading_books
  has_many :reviews, dependent: :destroy
  has_many :rakes
  has_many :likes
  has_many :requests
  has_many :comments

  def is_user? user
    self == user
  end

  class << self
    def digest string
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def authenticated? remember_token
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password? remember_token
  end

  def forget
    update_attributes remember_digest: nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout false, only: [:new]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
      :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, size: 80
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/index.html.erb
<%= will_paginate %>
  <ul class="users">
    <%= render @users %>
  </ul>
<%= will_paginate %>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
          data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
          aria-expanded="false">
          <span class="sr-only"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to t("project_name"), "#", {class: "navbar-brand"} %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li class="user-name"><span><%= current_user.name %></span></li>
            <li class="dropdown avatar-dropdown">
              <%= image_tag "admin/avatar3.png", class: "img-circle avatar",
                data: {toggle: "dropdown"},
                aria: {haspopup: "true", expanded: "true"} %>
              <ul class="dropdown-menu user-dropdown">
                <li><%= link_to t("account_profile"), "#" %></li>
                <li><%= link_to t("account_setting"), "#" %></li>
                <% if verify_user_access? %>
                  <li><%= link_to t("admin_section"), admin_root_path %></li>
                <% end %>
                <li role="separator" class="divider"></li>
                <li>
                  <%= link_to t("account_logout"), logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li class="user-name"><span><%= t "account_guest" %></span></li>
            <li class="dropdown avatar-dropdown">
              <%= image_tag "admin/avatar3.png", class: "img-circle avatar",
                data: {toggle: "dropdown"},
                aria: {haspopup: "true", expanded: "true"} %>
              <ul class="dropdown-menu user-dropdown">
                <li><%= link_to t("signin_button"), login_path %></li>
                <li><%= link_to t("account_sign_up"), signup_path %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <h1><%= t "account_sign_up" %></h1>
        <div class="col-md-6 col-md-offset-3">
          <%= form_for @user, url: signup_path do |f| %>
            <%= render "shared/error_messages", object: @user %>
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
            <%= f.label :email %>
            <%= f.email_field :email, class: "form-control" %>
            <%= f.label :password_user %>
            <%= f.password_field :password, class: "form-control" %>
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
            <%= f.submit t("btn_signup"), class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
    <footer class="footer container-fluid">
      <p><%= t "footer" %></p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>