config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "static_pages#home"
    resources :categories, except: [:show]
    resources :books
  end
  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  resources :users, except: [:destroy]
  resources :books, only: [:index, :show] do
    resources :reviews do
      resources :comments
    end
    resources :rates, except: [:destroy]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  scope :newest, ->{order created_at: :desc}

  validates :name, presence: true, length: {maximum: 50}, uniqueness: true

  has_many :books, dependent: :destroy

  class << self
    def search search
      if search
        where "name LIKE ?", "%#{search}%"
      else
        newest
      end
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :verify_access
  before_action :load_category, only: [:destroy, :update, :edit]
  layout "admin_application"

  def index
    @categories = Category.search(params[:key_seach]).newest
      .paginate page: params[:page], per_page: Settings.per_page
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    @category.save
    respond_to do |format|
      format.js
    end
  end

  def edit
    unless @category
      flash[:warning] = t "record_isnt_exist"
      redirect_to admin_categories_path
    end
  end

  def update
    if @category.update_attributes category_params
      flash[:info] = t "alert_result"
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    unless @category
      respond_to do |format|
        format.js {render "admin/shared/fail_update_or_del.js.erb"}
      end
    else
      @category.destroy
      respond_to do |format|
        format.js
      end
    end
  end

  private
  def category_params
    params.require(:category).permit :name
  end

  def load_category
    @category = Category.find_by id: params[:id]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_categories.html.erb
<table class="table table-striped table-bordered table-custom"
  cellspacing="0">
  <thead>
    <tr>
      <th class = "first-column"><%= t "no_number" %></th>
      <th><%= t "category_name" %></th>
      <th class = "last-column"><%= t "action" %></th>
    </tr>
  </thead>
  <tbody id = "body_table_data">
    <% @categories.each do |category| %>
      <tr>
        <td class = "first-column">
          <%= category.id %>
        </td>
        <td><%= category.name %></td>
        <td class = "last-column">
          <%= link_to t("edit_button"),
            edit_admin_category_path(category),
            class: "btn btn-warning btn-mn" %>
          <%= link_to t("delete_button"), admin_category_path(category),
             method: :delete, remote: true,
             data: {confirm: t("alert_confirm")},
             class: "btn btn-danger btn-mn btn-custom" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="col-md-12 top-20 padding-0 custom-div">
  <%= will_paginate %>
</div>

app/views/admin/categories/_category.html.erb
<tr>
  <td class = "first-column"><%= @category.id %></td>
  <td><%= @category.name %></td>
  <td class = "last-column">
    <%= link_to t("edit_button"), edit_admin_category_path(@category),
      class: "btn btn-warning btn-mn" %>
    <%= link_to t("delete_button"), admin_category_path(@category),
      method: :delete, remote: true,
      data: {confirm: t("alert_confirm")},
      class: "btn btn-danger btn-mn btn-custom" %>
  </td>
</tr>

app/views/admin/categories/_list.html.erb
<table class="table table-striped table-bordered table-custom" cellspacing="0">
  <thead>
    <tr>
      <th class = "first-column"><%= t "no_number" %></th>
      <th><%= t "category_name" %></th>
      <th class = "last-column"><%= t "action" %></th>
    </tr>
  </thead>
  <tbody id = "body_table_data">
    <% @categories.each do |category| %>
      <tr>
        <td class = "first-column"><%= category.id %></td>
        <td><%= category.name %></td>
        <td class = "last-column">
          <%= link_to t("edit_button"), edit_admin_category_path(category),
            class: "btn btn-warning btn-mn" %>
          <%= link_to t("delete_button"), admin_category_path(category),
            method: :delete, remote: true,
            data: {confirm: t("alert_confirm")},
            class: "btn btn-danger btn-mn btn-custom" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="col-md-12 top-20 padding-0 custom-div"><%= will_paginate %></div>

app/views/admin/categories/create.js.erb
<% if @category.errors.any? %>
  notify = $(".mess-area-add");
  notify.html("<%= j render "admin/shared/message_add", object: @category %>");
<% else %>
  tbody = $("#body_table_data");
  notify = $(".mess-area-add");
  tbody.prepend("<%= j render "admin/categories/category" %>")
  notify.html("<%= j render "admin/shared/message_add", object: @category %>");
  $(".reset-input").val("");
<% end %>

app/views/admin/categories/destroy.js.erb
notify = $(".mess-area-du");
notify.html("<%= j render "admin/shared/succ_del" %>");

app/views/admin/categories/edit.html.erb
<div class="col-md-12 top-20 padding-0">
  <div class="col-md-12">
    <div class="panel">
      <div class="panel-heading">
        <h3><%= t "edit_record" %></h3>
      </div>
      <div class="panel-body">
        <%= form_for [:admin, @category], url: admin_category_path do |f| %>
          <div class="row">
            <div class="col-md-6">
              <%= f.label :name %>
              <%= f.text_field :name, placeholder: t("category_name"),
                class: "form-control reset-input" %>
            </div>
            <div class = "clr"></div>
            <div class="col-md-6 top-20 padding-0">
              <div class="form-group col-md-3">
                <%= button_tag type: "submit",
                  class: "btn ripple btn-gradient btn-info" do %>
                  <div><span><%= t "update_button" %></span></div>
                <% end %>
              </div>
              <div class="form-group col-md-3">
                <%= button_tag type: "reset",
                  class: "btn ripple btn-gradient btn-default" do %>
                  <div><span><%= t "reset_button" %></span></div>
                <% end %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 mess-area-add">
              <% if @category.errors.any? %>
                <div class="alert alert-danger alert-custom">
                  <button type="button" class="close closeNotify">&times;</button>
                  <% @category.errors.full_messages.each do |msg| %>
                    <p><%= msg %></p>
                  <% end %>
                </div>
              <% end %>
            </div>
            <div class="col-md-6"></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="col-md-12 top-20 padding-0">
  <div class="col-md-12">
    <div class="panel">
      <div class="panel-heading">
        <h3><%= t "add_new" %></h3>
      </div>
      <div class="panel-body">
        <%= form_for [:admin, @category], remote: true do |f| %>
          <div class="row">
            <div class="col-md-6">
              <%= f.label :name %>
              <%= f.text_field :name, placeholder: t("category_name"),
                class: "form-control reset-input" %>
            </div>
            <div class = "clr"></div>
            <div class="col-md-6 top-20 padding-0">
              <div class="form-group col-md-3">
                <%= button_tag type: "submit",
                  class: "btn ripple btn-gradient btn-info" do %>
                  <div><span><%= t "add_button" %></span></div>
                <% end %>
              </div>
              <div class="form-group col-md-3">
                <%= button_tag type: "reset",
                  class: "btn ripple btn-gradient btn-default" do %>
                  <div><span><%= t "reset_button" %></span></div>
                <% end %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 mess-area-add">
            </div>
            <div class="col-md-6">
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="col-md-12 top-20 padding-0">
  <div class="col-md-12">
    <div class="panel">
      <div class="panel-heading">
        <h3><%= t "show" %></h3>
      </div>
      <div class="panel-body">
        <div class="col-md-6 mess-area-du padding-0">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>">
              <button type="button" class="close closeNotify">&times;</button>
              <%= message %>
            </div>
          <% end %>
        </div>
        <div class="col-md-12 col-md-12-custom top-20 padding-0">
          <div class="col-md-4 padding-0">
            <%= form_tag admin_categories_path, method: "GET",
              id: "my_form_search" do %>
              <%= text_field_tag :key_seach, params[:key_seach],
                placeholder: t("category_name"),
                class: "form-control reset-input" %>
              <span class="glyphicon glyphicon-search form-control-feedback">
              </span>
            <% end %>
          </div>
        </div>
        <div class = "clr"></div>
        <div class="responsive-table sort-table">
          <%= render "list" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/index.js.erb
$(".sort-table").html("<%= j render "admin/categories/list" %>");