config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "static_pages#home"
    resources :categories, except: [:show]
    resources :books
  end
  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  resources :users, except: [:destroy]
  resources :books, only: [:index, :show] do
    resources :reviews do
      resources :comments
    end
    resources :rates, except: [:destroy]
  end
end

app/views/layouts/_admin_header.html.erb
<nav class="navbar navbar-default header navbar-fixed-top">
  <div class="col-md-12 nav-wrapper">
    <div class="navbar-header navbar-header-custom">
      <%= link_to t("project_name"), admin_root_path, {class: "navbar-brand"} %>
      <ul class="nav navbar-nav navbar-right user-nav">
        <li class="user-name"><span><%= current_user.name %></span></li>
        <li class="dropdown avatar-dropdown">
          <%= image_tag "admin/avatar3.png", class: "img-circle avatar",
            data: {toggle: "dropdown"},
            aria: {haspopup: "true", expanded: "true"} %>
          <ul class="dropdown-menu user-dropdown">
            <li><%= link_to t("account_setting"), "#" %></li>
            <li><%= link_to t("user_section"), root_path %></li>
            <li role="separator" class="divider"></li>
            <li>
              <%= link_to t("account_logout"), logout_path, method: :delete %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_admin_leftbar.html.erb
<div id="left-menu">
  <div class="sub-left-menu scroll">
    <ul class="nav nav-list">
      <li>
        <div class="left-bg"></div>
      </li>
      <li class="ripple"><%= link_to t("menu_home"), admin_root_path %></li>
      <li class="ripple"><%= link_to t("menu_cate"), admin_categories_path %></li>
      <li class="ripple"><%= link_to t("menu_book"), admin_books_path %></li>
      <li class="ripple"><%= link_to t("menu_review"), "#" %></li>
      <li class="ripple"><%= link_to t("menu_user"), "#" %></li>
      <li class="ripple"><%= link_to t("menu_request"), "#" %></li>
    </ul>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer container-fluid">
  <p><%= t "footer" %></p>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
        data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
        aria-expanded="false">
        <span class="sr-only"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t("project_name"), root_path, {class: "navbar-brand"} %>
    </div>
    <div class="collapse navbar-collapse navbar-custom"
      id="bs-example-navbar-collapse-1">
      <%= form_tag books_path, method: "GET", id: "search_book",
        class: "navbar-form navbar-left" do %>
        <%= text_field_tag :search, params[:search],
          placeholder: t("book_name"), class: "form-control" %>
          <div id = "result_search"></div>
      <% end %>
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <%= link_to t("menu_book"), books_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"
            role="button" aria-haspopup="true" aria-expanded="false">
            <%= t "menu_cate" %>
          </a>
          <ul class="dropdown-menu">
            <% @categories.each do |category| %>
              <li>
                <%= link_to category.name, books_path(category: category.id) %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="user-name"><span><%= current_user.name %></span></li>
          <li class="dropdown avatar-dropdown">
            <%= image_tag "admin/avatar3.png", class: "img-circle avatar",
              data: {toggle: "dropdown"},
              aria: {haspopup: "true", expanded: "true"} %>
            <ul class="dropdown-menu user-dropdown">
              <li><%= link_to t("account_profile"), "#" %></li>
              <li><%= link_to t("account_setting"), "#" %></li>
              <% if verify_user_access? %>
                <li><%= link_to t("admin_section"), admin_root_path %></li>
              <% end %>
              <li role="separator" class="divider"></li>
              <li>
                <%= link_to t("account_logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="user-name"><span><%= t "account_guest" %></span></li>
          <li class="dropdown avatar-dropdown">
            <%= image_tag "admin/avatar3.png", class: "img-circle avatar",
              data: {toggle: "dropdown"},
              aria: {haspopup: "true", expanded: "true"} %>
            <ul class="dropdown-menu user-dropdown">
              <li><%= link_to t("signin_button"), login_path %></li>
              <li><%= link_to t("account_sign_up"), "/signup" %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= t "project_name" %></title><meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": true %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": true %>
    <%= csrf_meta_tags %>
  </head>
  <body id="mimin" class="dashboard">
    <%= render "layouts/admin_header" %>
    <%= render "layouts/admin_leftbar" %>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>